import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { XMLParser, XMLValidator } from 'fast-xml-parser';
import { designFingerprint, projectFingerprint, readBuildState } from '../build/builder';
import { ResolvedProject, portablePath, resolveProject, writeConfig } from '../project/config';
import { tclString } from '../project/sync';
import { Toolchain } from '../toolchain/detect';
import { TclSession } from '../toolchain/tclSession';
import { IoAssignment, IoData, IoPort } from '../views/previewModel';
import { validateIoAssignments } from './validation';

export const IO_XDC_HEADER = '# Generated by Vivado for VS Code I/O Planning';
const checkpointFor = (project: ResolvedProject) => path.join(project.projectDir, `${project.config.name}.runs`, 'synth_1', `${project.config.top}.dcp`);

export function ioQueryTcl(project: ResolvedProject, filename: string): string {
  return `
proc vscode_io_xml {value} {
  return [string map {& &amp; < &lt; > &gt; \\" &quot; ' &apos;} $value]
}
set io_status [catch {
  open_checkpoint ${tclString(checkpointFor(project))}
  if {![string equal -nocase [get_property PART [current_design]] ${tclString(project.config.part)}]} {
    error "The synthesized checkpoint uses a different part. Run synthesis again."
  }
  set ports [get_ports -quiet]
  if {[llength $ports] > 0} {
    set_property PACKAGE_PIN {} $ports
    set_property IOSTANDARD {} $ports
  }
  set io_critical [get_msg_config -count -severity {CRITICAL WARNING}]
  set io_errors [get_msg_config -count -severity ERROR]
  ${project.files.constraints.map(file => `read_xdc ${tclString(file)}`).join('\n  ')}
  if {[get_msg_config -count -severity {CRITICAL WARNING}] > $io_critical || [get_msg_config -count -severity ERROR] > $io_errors} {
    error "Vivado could not apply all constraints. Correct the errors in Vivado Output before I/O Planning."
  }
  set io_file [open ${tclString(filename)} w]
  fconfigure $io_file -encoding utf-8
  puts $io_file "<io part=\\"[vscode_io_xml [get_property PART [current_design]]]\\">"
  foreach pin [get_package_pins -quiet -filter {IS_GENERAL_PURPOSE == 1 && IS_BONDED == 1}] {
    puts $io_file "<pin name=\\"[vscode_io_xml [get_property NAME $pin]]\\" bank=\\"[get_property BANK $pin]\\" function=\\"[vscode_io_xml [get_property PIN_FUNC $pin]]\\" clock=\\"[get_property IS_CLK_CAPABLE $pin]\\" mate=\\"[get_property DIFF_PAIR_PIN $pin]\\"/>"
  }
  foreach bank [get_iobanks -quiet] {
    puts $io_file "<bank name=\\"[get_property NAME $bank]\\" type=\\"[get_property BANK_TYPE $bank]\\" standards=\\"[vscode_io_xml [get_io_standards -quiet -of_objects $bank]]\\"/>"
  }
  foreach standard [get_io_standards -quiet] {
    puts $io_file "<standard name=\\"[get_property NAME $standard]\\" directions=\\"[get_property DIRECTION $standard]\\" vccoIn=\\"[get_property VCCO_IN $standard]\\" vccoOut=\\"[get_property VCCO_OUT $standard]\\"/>"
  }
  foreach port $ports {
    puts $io_file "<port name=\\"[vscode_io_xml [get_property NAME $port]]\\" direction=\\"[get_property DIRECTION $port]\\" pin=\\"[vscode_io_xml [get_property PACKAGE_PIN $port]]\\" standard=\\"[get_property IOSTANDARD $port]\\"/>"
  }
  puts $io_file "</io>"
  close $io_file
  unset io_file
} io_error io_options]
if {[info exists io_file]} { catch {close $io_file}; unset io_file }
catch {close_project}
if {$io_status} { return -options $io_options $io_error }
`;
}

export function parseIoQuery(xml: string, part: string): Pick<IoData, 'ports' | 'pins' | 'banks' | 'standards'> {
  if (Buffer.byteLength(xml) > 8 * 1024 * 1024 || /<!DOCTYPE|<!ENTITY/i.test(xml) || XMLValidator.validate(xml) !== true) throw new Error('Invalid I/O device query.');
  const data = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '', parseAttributeValue: false,
    isArray: (name, _path, _leaf, attribute) => !attribute && ['pin', 'port', 'bank', 'standard'].includes(name),
  }).parse(xml).io;
  if (!data || typeof data.part !== 'string' || data.part.toLowerCase() !== part.toLowerCase()) throw new Error('I/O device query does not match the project part. Run synthesis again.');
  const text = (value: unknown): string => {
    if (typeof value !== 'string' || value.length > 4096) throw new Error('Invalid I/O device property.');
    return value;
  };
  const direction = (value: unknown): IoPort['direction'] => {
    if (value !== 'IN' && value !== 'OUT' && value !== 'INOUT') throw new Error('Invalid I/O port direction.');
    return value;
  };
  const words = (value: unknown) => text(value).split(/\s+/).filter(Boolean);
  const voltage = (value: unknown) => {
    const number = Number(text(value));
    if (!Number.isFinite(number) || number < 0 || number > 10) throw new Error('Invalid I/O standard voltage.');
    return number;
  };
  const result = {
    pins: (data.pin || []).map((pin: Record<string, unknown>) => ({ name: text(pin.name), bank: text(pin.bank), function: text(pin.function), clock: pin.clock === '1', differentialMate: text(pin.mate) })),
    banks: (data.bank || []).map((bank: Record<string, unknown>) => ({ name: text(bank.name), type: text(bank.type), standards: words(bank.standards) })),
    standards: (data.standard || []).map((standard: Record<string, unknown>) => ({ name: text(standard.name), directions: words(standard.directions), vccoIn: voltage(standard.vccoIn), vccoOut: voltage(standard.vccoOut) })),
    ports: (data.port || []).map((port: Record<string, unknown>) => ({ name: text(port.name), direction: direction(port.direction), packagePin: text(port.pin), ioStandard: port.standard === 'DEFAULT' ? '' : text(port.standard) })),
  };
  if (!result.pins.length || result.pins.length > 5000 || result.ports.length > 2000 || result.standards.length > 500) throw new Error('Unsupported I/O device size.');
  for (const group of [result.pins, result.ports, result.banks, result.standards]) {
    if (new Set(group.map((item: { name: string }) => item.name)).size !== group.length) throw new Error('Duplicate I/O device entries.');
    group.sort((a: { name: string }, b: { name: string }) => a.name.localeCompare(b.name, 'en', { numeric: true }));
  }
  return result;
}

async function ioRevision(project: ResolvedProject, tools: Toolchain): Promise<string> {
  const state = await readBuildState(project.root);
  if (!state?.designFingerprint || state.designFingerprint !== await designFingerprint(project, tools)) {
    throw new Error('Run Synthesize before I/O Planning: the design is missing, outdated, or was built with an older extension.');
  }
  const checkpoint = await fs.stat(checkpointFor(project)).catch(() => { throw new Error('The synthesized checkpoint is missing. Run Synthesize again.'); });
  return createHash('sha256').update(await projectFingerprint(project, tools)).update(`${checkpoint.size}|${checkpoint.mtimeMs}|${state.completedAt}`).digest('hex');
}

export async function readIoPlan(project: ResolvedProject, tools: Toolchain, session: TclSession, signal?: AbortSignal): Promise<IoData> {
  const revision = await ioRevision(project, tools);
  const output = path.join(project.root, '.vivado', 'io', 'device.xml');
  await fs.mkdir(path.dirname(output), { recursive: true });
  await session.execute(ioQueryTcl(project, output), signal, 90000);
  if (revision !== await ioRevision(await resolveProject(project.root), tools)) throw new Error('Project changed during the I/O query. Reload I/O Planning.');
  const queried = parseIoQuery(await fs.readFile(output, 'utf8'), project.config.part);
  return {
    kind: 'ioPlanning', title: project.config.top, source: checkpointFor(project), part: project.config.part,
    generatedAt: new Date().toISOString(), revision, ...queried,
    constraintFile: project.config.ioConstraints || 'constraints/io-planning.xdc',
  };
}

export function ioConstraintsTcl(data: Pick<IoData, 'part'>, assignments: IoAssignment[]): string {
  const lines = [IO_XDC_HEADER, `# Part: ${data.part}`, '# Pin assignments only; board voltages and timing constraints require separate verification.', ''];
  const targets = assignments.map(port => {
    // Exact regexp matching prevents bus brackets and escaped identifiers becoming globs.
    const pattern = '^' + port.name.replace(/[\\^$.*+?()[\]{}|]/g, '\\$&') + '$';
    return `[get_ports -quiet -regexp ${tclString(pattern)}]`;
  });
  // Release all old assignments first so swapping two occupied pins is valid.
  targets.forEach((target, index) => {
    lines.push(`set_property PACKAGE_PIN {} ${target}`);
    if (!assignments[index].ioStandard) lines.push(`set_property IOSTANDARD {} ${target}`);
  });
  assignments.forEach((port, index) => {
    for (const [property, value] of [['PACKAGE_PIN', port.packagePin], ['IOSTANDARD', port.ioStandard]]) {
      if (value) lines.push(`set_property ${property} ${tclString(value)} ${targets[index]}`);
    }
  });
  return lines.join('\n') + '\n';
}

export async function saveIoPlan(root: string, tools: Toolchain, snapshot: IoData, entries: unknown, filename: string): Promise<IoData> {
  const project = await resolveProject(root);
  if (snapshot.part !== project.config.part || snapshot.revision !== await ioRevision(project, tools)) throw new Error('Project or constraints changed. Reload I/O Planning before saving.');
  const checked = validateIoAssignments(snapshot, entries);
  if (checked.errors.length) throw new Error(checked.errors.join('\n'));
  const relative = path.relative(root, filename);
  if (!relative || relative === '..' || relative.startsWith('..' + path.sep) || path.isAbsolute(relative) || !/\.xdc$/i.test(filename) || relative.split(path.sep).includes('.vivado')) {
    throw new Error('Save the XDC inside the workspace, outside .vivado.');
  }
  const previous = await fs.readFile(filename, 'utf8').catch((error: NodeJS.ErrnoException) => { if (error.code !== 'ENOENT') throw error; return undefined; });
  if (previous !== undefined && !previous.startsWith(IO_XDC_HEADER + '\n') && !previous.startsWith(IO_XDC_HEADER + '\r\n')) {
    throw new Error('This file was not created by I/O Planning. Choose a new filename to preserve existing constraints.');
  }
  const content = ioConstraintsTcl(snapshot, checked.assignments);
  await fs.mkdir(path.dirname(filename), { recursive: true });
  const temporary = `${filename}.${randomUUID()}.tmp`;
  await fs.writeFile(temporary, content, { encoding: 'utf8', flag: 'wx' });
  try {
    await fs.rename(temporary, filename);
    project.config.ioConstraints = portablePath(relative);
    await writeConfig(root, project.config);
  } catch (error) {
    if (await fs.readFile(filename, 'utf8').catch(() => '') === content) {
      if (previous === undefined) await fs.rm(filename, { force: true });
      else await fs.writeFile(filename, previous, 'utf8');
    }
    throw error;
  } finally { await fs.rm(temporary, { force: true }); }
  const assignments = new Map(checked.assignments.map(port => [port.name, port]));
  return { ...snapshot, constraintFile: portablePath(relative), revision: await ioRevision(await resolveProject(root), tools),
    ports: snapshot.ports.map(port => ({ ...port, ...assignments.get(port.name)! })),
  };
}
